### ISSUE TITLE
dropdown changes

### ISSUE THREAD

**Issue by msj121** [derbyjs/d-bootstrap#31]
I have a dropdown with value changes. It opens, closes and changes as expected, except the label value doesn't change....

       <div class="form-group">
          <label for="inputGender" class="col-sm-3 control-label">Gender</label>
          <div class="col-sm-2">
            <dropdown value="{{_page.user.gender}}">
              <option value="None">None</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
            </dropdown>
          </div>
        </div>

Any thoughts?

**Comment by dadisn** [comment]
It seems you are using the dropdown component incorrectly. You need to define all options as an array of objects, where each object contains a `value`, `content` for setting a display value and optionally `class` for styling. You then pass this array onto the component using the options flag. Try something like the following.

In your page component's init/create function:
```javascript
model.set('_page.options', [
    {value: 'None', content: 'None'}
  , {value: 'Male', content: 'Male'}
  , {value: 'Female', content: 'Female'}]
);
```

In your template:
```html
<dropdown options="{{_page.options}}" value="{{_page.user.gender}}"></dropdown>
```

**Comment by msj121** [comment]
Great! That worked, thank you so much!
